export type Vec2 = { x: number; y: number };
export type UpgradePath = 'A' | 'B' | 'C';
export type TargetingMode = 'first' | 'last' | 'strongest' | 'weakest' | 'fastest' | 'boss';

export const TARGETING_MODES: TargetingMode[] = ['first', 'last', 'strongest', 'weakest', 'fastest', 'boss'];

export const TARGETING_LABEL: Record<TargetingMode, string> = {
  first: 'FIRST',
  last: 'LAST',
  strongest: 'STRONGEST',
  weakest: 'WEAKEST',
  fastest: 'FASTEST',
  boss: 'BOSS'
};

export enum EmotionType {
  Anger = 'anger',
  Sadness = 'sadness',
  Joy = 'joy',
  Fear = 'fear',
  Calm = 'calm',
  Hope = 'hope',
  Disgust = 'disgust',
  Guilt = 'guilt_tower',
  Trust = 'trust',
  Shame = 'shame_tower',
  Love = 'love',
  Pride = 'pride'
}

export const EMOTION_TYPES: EmotionType[] = [
  EmotionType.Anger,
  EmotionType.Sadness,
  EmotionType.Joy,
  EmotionType.Fear,
  EmotionType.Calm,
  EmotionType.Hope,
  EmotionType.Disgust,
  EmotionType.Guilt,
  EmotionType.Trust,
  EmotionType.Shame,
  EmotionType.Love,
  EmotionType.Pride
];

export enum EnemyKind {
  Doubtling = 'doubtling',
  PanicRunner = 'panic',
  GuiltGiant = 'guilt',
  ShameSwarm = 'shame',
  EnvyLeech = 'envy',
  BurnoutBrute = 'burnout',
  VoidWraith = 'void',
  Overthinker = 'overthinker',
  NumbOne = 'numb',
  Spiral = 'spiral',
  Mask = 'mask',
  BurnoutBoss = 'burnout_boss'
}

export const BOSS_KINDS: EnemyKind[] = [
  EnemyKind.Spiral,
  EnemyKind.Mask,
  EnemyKind.BurnoutBoss
];

export function isBossKind(kind: EnemyKind): boolean {
  return kind === EnemyKind.Spiral || kind === EnemyKind.Mask || kind === EnemyKind.BurnoutBoss;
}

export interface DamagePacket {
  amount: number;
  source: EmotionType;
  /** speed multiplier (e.g. 0.5 = 50% slower); higher = stronger slow when lower number */
  slow?: number;
  /** seconds of slow */
  slowDuration?: number;
  /** seconds of stun */
  stunDuration?: number;
  /** 0..1 chance to apply fear stun */
  fearChance?: number;
  /** poison damage per second */
  poisonDps?: number;
  /** seconds of poison */
  poisonDuration?: number;
  /** incoming damage multiplier while shredded */
  armorShred?: number;
  /** seconds of armor shred */
  armorShredDuration?: number;
  /** repeated-hit mark strength */
  guiltMark?: number;
  /** execute enemies at or below this HP ratio after a guilt hit */
  guiltExecuteThreshold?: number;
  /** stability shield generated by Trust hits */
  coreShield?: number;
  /** Trust suppression for Panic/Void special movement */
  trustAnchorDuration?: number;
  /** Shame bonus when the target is packed inside a group */
  shameGroupRadius?: number;
  shameGroupDamageMul?: number;
}
